package com.example.java.web;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.3.4
 * 2020-01-02T11:48:07.246+03:30
 * Generated source version: 3.3.4
 *
 */
@WebServiceClient(name = "paymentService",
                  wsdlLocation = "file:/C:/Users/AhmadReza/IdeaProjects/java-web/session10/client/src/main/resources/wsdl.wsdl",
                  targetNamespace = "http://session10.web.java.nikamooz.com/")
public class PaymentService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://session10.web.java.nikamooz.com/", "paymentService");
    public final static QName PaymentServiceImplPort = new QName("http://session10.web.java.nikamooz.com/", "PaymentServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/AhmadReza/IdeaProjects/java-web/session10/client/src/main/resources/wsdl.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(PaymentService_Service.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/AhmadReza/IdeaProjects/java-web/session10/client/src/main/resources/wsdl.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public PaymentService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public PaymentService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PaymentService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    public PaymentService_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public PaymentService_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public PaymentService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns PaymentService
     */
    @WebEndpoint(name = "PaymentServiceImplPort")
    public PaymentService getPaymentServiceImplPort() {
        return super.getPort(PaymentServiceImplPort, PaymentService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PaymentService
     */
    @WebEndpoint(name = "PaymentServiceImplPort")
    public PaymentService getPaymentServiceImplPort(WebServiceFeature... features) {
        return super.getPort(PaymentServiceImplPort, PaymentService.class, features);
    }

}
