package com.example.java.web;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.4
 * 2020-01-02T11:48:07.099+03:30
 * Generated source version: 3.3.4
 *
 */
@WebService(targetNamespace = "http://session10.web.java.nikamooz.com/", name = "PaymentService")
@XmlSeeAlso({ObjectFactory.class})
public interface PaymentService {

    @WebMethod
    @RequestWrapper(localName = "withdraw", targetNamespace = "http://session10.web.java.nikamooz.com/", className = "com.nikamooz.java.web.session10.Withdraw")
    @ResponseWrapper(localName = "withdrawResponse", targetNamespace = "http://session10.web.java.nikamooz.com/", className = "com.nikamooz.java.web.session10.WithdrawResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean withdraw(

        @WebParam(name = "arg0", targetNamespace = "")
        Payment arg0
    );

    @WebMethod
    @RequestWrapper(localName = "deposit", targetNamespace = "http://session10.web.java.nikamooz.com/", className = "com.nikamooz.java.web.session10.Deposit")
    @ResponseWrapper(localName = "depositResponse", targetNamespace = "http://session10.web.java.nikamooz.com/", className = "com.nikamooz.java.web.session10.DepositResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean deposit(

        @WebParam(name = "arg0", targetNamespace = "")
        Payment arg0
    );
}
